[FIX] typescript compile errors
Fixes the following errors when compiling typescript:

```
src/pages/project/models/file/ProjectFileHelper.ts:46:30 - error TS2345: Argument of type 'ArrayBufferLike' is not assignable to parameter of type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength

46   return arrayBufferToBase64(volumeData.buffer);
                                ~~~~~~~~~~~~~~~~~

src/pages/project/models/file/ProjectFileHelper.ts:112:29 - error TS2345: Argument of type 'ArrayBufferLike' is not assignable to parameter of type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength

112  return arrayBufferToBase64(saveData.buffer);
                                ~~~~~~~~~~~~~~~
```